/**
 * @NApiVersion 2.1
 */

define([],function(){

    const FIELD_ID = {};

    const INTERFACE = {};

    INTERFACE.FORM = {};
    INTERFACE.FORM.TITLE = 'Reporte DIOT';

    INTERFACE.FORM.FIELDS = {};

    INTERFACE.FORM.BUTTONS = {};
    INTERFACE.FORM.BUTTONS.GENERAR = {};
    INTERFACE.FORM.BUTTONS.GENERAR.ID = 'btn_generar_diot';
    INTERFACE.FORM.BUTTONS.GENERAR.LABEL = 'Generar';
    INTERFACE.FORM.BUTTONS.GENERAR.FUNCTION = 'generarReporte';

    
    FIELD_ID.PANTALLA = {};
    FIELD_ID.PANTALLA.GRUPO_DATOS = 'fieldgroupid_datos';
    FIELD_ID.PANTALLA.SUBSIDIARIA = 'custpage_subsi';
    FIELD_ID.PANTALLA.PERIODO = 'custpage_period';

    const RECORD_INFO = {};

    RECORD_INFO.SUBSIDIARY_RECORD = {};
    RECORD_INFO.SUBSIDIARY_RECORD.ID = 'subsidiary';
    RECORD_INFO.SUBSIDIARY_RECORD.FIELDS = {};
    RECORD_INFO.SUBSIDIARY_RECORD.FIELDS.INACTIVE = 'isinactive';
    RECORD_INFO.SUBSIDIARY_RECORD.FIELDS.ID = 'internalid';
    RECORD_INFO.SUBSIDIARY_RECORD.FIELDS.NAME = 'name';

    RECORD_INFO.ACCOUNTINGPERIOD_RECORD = {};
    RECORD_INFO.ACCOUNTINGPERIOD_RECORD.ID = 'accountingperiod';
    RECORD_INFO.ACCOUNTINGPERIOD_RECORD.FIELDS = {};
    RECORD_INFO.ACCOUNTINGPERIOD_RECORD.FIELDS.INACTIVE = 'isinactive';
    RECORD_INFO.ACCOUNTINGPERIOD_RECORD.FIELDS.ID = 'internalid';
    RECORD_INFO.ACCOUNTINGPERIOD_RECORD.FIELDS.NAME = 'periodname';

    const SCRIPTS_INFO = {};

    SCRIPTS_INFO.MAP_REDUCE = {};
    SCRIPTS_INFO.MAP_REDUCE.SCRIPT_ID = 'customscript_tko_generate_diot_mr';
    SCRIPTS_INFO.MAP_REDUCE.DEPLOYMENT_ID = 'customdeploy_tko_diot_generate_1';
    SCRIPTS_INFO.MAP_REDUCE.PARAMETERS = {};
    SCRIPTS_INFO.MAP_REDUCE.PARAMETERS.SUBSIDIARY = 'custscript_tko_diot_subsidiary';
    SCRIPTS_INFO.MAP_REDUCE.PARAMETERS.PERIOD = 'custscript_tko_diot_periodo';
    SCRIPTS_INFO.MAP_REDUCE.PARAMETERS.COMPANY_NAME = 'custscript_tko_diot_company_name';

    SCRIPTS_INFO.SUITELET = {};
    SCRIPTS_INFO.SUITELET.SCRIPT_ID = 'customscript_tko_diot_view_sl';
    SCRIPTS_INFO.SUITELET.DEPLOYMENT_ID = 'customdeploy_tko_diot_view_sl';
    SCRIPTS_INFO.SUITELET.PARAMETERS = {};
    SCRIPTS_INFO.SUITELET.PARAMETERS.SUBSIDIARY = 'subsidiaria';
    SCRIPTS_INFO.SUITELET.PARAMETERS.PERIOD = 'periodo';

    SCRIPTS_INFO.CLIENT = {};
    SCRIPTS_INFO.CLIENT.FILE_NAME = 'tko_diot_cs.js';

    const RUNTIME = {};

    RUNTIME.FEATURES = {};
    RUNTIME.FEATURES.SUBSIDIARIES = 'subsidiaries';

    return {
        INTERFACE: INTERFACE,
        FIELD_ID: FIELD_ID,
        RECORD_INFO: RECORD_INFO,
        SCRIPTS_INFO: SCRIPTS_INFO,
        RUNTIME: RUNTIME
    }
});